name: defnicks
version: 1.0.0
main: com.defgodqe.defnicks.DefNicks
api-version: '1.21'
author: defgodqe
website: https://github.com/defgodqe-arch/defnicks
description: Displays EssentialsX nicknames in the TAB tablist.
softdepend:
  - Essentials
  - TAB

commands:
  defnicks:
    description: Configure TAB to display Essentials nicknames.
    usage: /defnicks
    permission: defnicks.admin

permissions:
  defnicks.admin:
    description: Allows configuration of defnicks.
    default: op
